/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResolveDuplicatesRouteImport } from './routes/resolve-duplicates'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ClerkRouteImport } from './routes/clerk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreSchoolIdRouteImport } from './routes/explore.$schoolId'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolveDuplicatesRoute = ResolveDuplicatesRouteImport.update({
  id: '/resolve-duplicates',
  path: '/resolve-duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRoute = ClerkRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSchoolIdRoute = ExploreSchoolIdRouteImport.update({
  id: '/explore/$schoolId',
  path: '/explore/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/clerk': typeof ClerkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resolve-duplicates': typeof ResolveDuplicatesRoute
  '/scan': typeof ScanRoute
  '/explore/$schoolId': typeof ExploreSchoolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/clerk': typeof ClerkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resolve-duplicates': typeof ResolveDuplicatesRoute
  '/scan': typeof ScanRoute
  '/explore/$schoolId': typeof ExploreSchoolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/clerk': typeof ClerkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resolve-duplicates': typeof ResolveDuplicatesRoute
  '/scan': typeof ScanRoute
  '/explore/$schoolId': typeof ExploreSchoolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/clerk'
    | '/reset-password'
    | '/resolve-duplicates'
    | '/scan'
    | '/explore/$schoolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/clerk'
    | '/reset-password'
    | '/resolve-duplicates'
    | '/scan'
    | '/explore/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/clerk'
    | '/reset-password'
    | '/resolve-duplicates'
    | '/scan'
    | '/explore/$schoolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClerkRoute: typeof ClerkRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResolveDuplicatesRoute: typeof ResolveDuplicatesRoute
  ScanRoute: typeof ScanRoute
  ExploreSchoolIdRoute: typeof ExploreSchoolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolve-duplicates': {
      id: '/resolve-duplicates'
      path: '/resolve-duplicates'
      fullPath: '/resolve-duplicates'
      preLoaderRoute: typeof ResolveDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$schoolId': {
      id: '/explore/$schoolId'
      path: '/explore/$schoolId'
      fullPath: '/explore/$schoolId'
      preLoaderRoute: typeof ExploreSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClerkRoute: ClerkRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResolveDuplicatesRoute: ResolveDuplicatesRoute,
  ScanRoute: ScanRoute,
  ExploreSchoolIdRoute: ExploreSchoolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
